### ISSUE TITLE
Pointer Down of Rive Artboard is no more accessible in Unreal Engine 5.3. [Awaiting Response]

### ISSUE THREAD

**Issue by AbdulMueed19** [rive-app/rive-unreal-examples#3]
![image](https://github.com/rive-app/rive-unreal-examples/assets/81902241/19f5678c-5fe5-46da-8065-9eed6f41de19)

Any ideas what should i do

@kuzi117 @schetle @Batname @paulmaurious @Voulz

**Comment by Voulz** [comment]
Hi @AbdulMueed19, `URiveArtboard::PointerDown` is currently only available in the `development` branch of the plugin.
It should be merged soon in the `main` branch.
https://github.com/rive-app/rive-unreal/blob/development/Source/RiveCore/Public/RiveArtboard.h#L100

**Comment by AbdulMueed19** [comment]
@Voulz Thanks for the reply! I just need a bit more information. Will Rive start supporting DirectX12 as the RHI in the next merge? current X11 support is not supporting our project.

**Comment by Voulz** [comment]
The `rive-renderer` does not yet support DX12 but the team is working on it. It will be implemented in Unreal once the library supports it, but there is not an official timeframe.
The next merge will merge the latest `dev` branch to `main` in the coming days (to make functions like `PointerDown` available), but DX12 will not be part of that update, as per the above.
